### ISSUE TITLE
Implement common tailwind config in tutors-home

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#106]
Implement the common tailwind config from tutors-configs in the tutors-home package.

You can see the implementation of this in action on the tutors-course-reader package.

**Comment by Fan** [comment]
I'll take this! Looking to get involved a bit more and it seems like an ok one to get started with! 
https://github.com/tutors-sdk/tutors/pull/109

**Comment by jordharr** [comment]
Great, issue assigned to you @Fan! :)
