### ISSUE TITLE
Implement common tailwind config in tutors-time-reader

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#107]
Implement the common tailwind config from tutors-configs in the tutors-time-reader package.

You can see the implementation of this in action on the tutors-course-reader package.

**Comment by bonjo7** [comment]
[PR-115](https://github.com/tutors-sdk/tutors/pull/115)

**Comment by bonjo7** [comment]
[PR 116](https://github.com/tutors-sdk/tutors/pull/116)

**Comment by jordharr** [comment]
Nice work @bonjo7  -  thanks for the contribution
