### ISSUE TITLE
Add the feature of cliping code in markdown

### ISSUE THREAD

**Issue by H-Blues** [tutors-sdk/tutors#225]
HI, I am an international student in SETU, and my major is software engineering. 
Really appreciate this project. Here is a suggestion of adding the feature of cliping code in markdown in tutor-reader.

I found that in `packages/tutors-reader-lib/src/utils/markdown-utils.ts`, `showdown` is used to convert markdown to html. Here is a simple plugin to implement the function of copying code in markdown: [showdown-copy-code](https://www.npmjs.com/package/showdown-copy-code).

Hope this suggestion helpful.

Kind Regards.

**Comment by jordharr** [comment]
Great suggestion. I'll get working on this today.

**Comment by jordharr** [comment]
Fix for this has been merged, thanks for the suggestion @H-Blues

**Comment by H-Blues** [comment]
Looks good! Thank you for your updating.
