### ISSUE TITLE
Simplify tutors-ui components & create storybook stories

### ISSUE THREAD

**Issue by jouwdan** [tutors-sdk/tutors#292]
Now that we have storybook set up and configured, we need to simplify the component in the tutors-ui package (ie make them more generic) and create stories for the components.

This package follows the atomic design methodology, so best to work on atoms first, before moving on to Molecules & Organisms.

storybook production deploy: https://ui.tutors.dev/

Instructions to run SB locally:

`npm i`

`cd packages/tutors-ui`

`npm run storybook`

**Comment by jordharr** [comment]
All work on this is to be done on the attached development branch ( feat/storybook-components )
