### ISSUE TITLE
Few upper bar icons in tutors-html

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#386]
As of tutors-html@2.6.3, the only icons that can be used on the upper left bar are Slack, YouTube and Moodle, as seen in
https://github.com/tutors-sdk/tutors/blob/f73645f41d5758db8bb10830a92e6c7a5bb774bb/cli/tutors-html/src/views/components/navigators/support/Companions.njk

I unsuccessfully tried to use other icons such as the ones listed in [tutors-sdk/tutors-template/properties.yaml](https://github.com/tutors-sdk/tutors-template/blob/master/properties.yaml). Neither the ones for Teams or Piazza display on the official deployment of the tutors-template website at https://tutors-sdk.github.io/tutors-template/, despite being listed on the aforementioned file.

As workaround, is there a way to use custom svg icons in tutors-html for this particular situation? Are there plans for the icon selection of tutors-html to be expanded?

**Comment by Depal1** [comment]
Answering my second question, I guess there are no such plans since tutors-html will be eventually replaced. https://github.com/tutors-sdk/tutors/issues/348

**Comment by tc-565** [comment]
Answering my second question, I guess there are no such plans since tutors-html will be eventually replaced, as stated in [#348](https://github.com/tutors-sdk/tutors/issues/348).

**Comment by edeleastar** [comment]
Thanks for the suggestion. In fact we will strive to implement this in tutors-publish-html. Reopening the issue again.

**Comment by edeleastar** [comment]
Hi @tc-565 - this is fixed now. See:
- [Static Reference Course](https://tutors-reference-course-html.netlify.app/)
From this yaml file:
- https://github.com/tutors-sdk/tutors-reference-course/blob/main/properties.yaml
