### ISSUE TITLE
tutors-publish-html website build error on note

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#391]
Building courses with https://github.com/tutors-sdk/tutors/pull/388 tutors-publish-html@3.0.1 and Node 20.5.0 may fail upon reaching a note card. I haven't been able to identify what makes these notes special in order to trigger this issue since there are notes which don't trigger it. This issue is not present in tutors-html@2.6.3.

I have submitted an example of a course with a note that triggers the aforementioned issue at:
https://github.com/tc-565/tutors-publish-html-regression-testing

I attach the error message too:

```
% tutors-html
Static course generator tutors-publish-html: 3.0.1 (tutors-gen-lib: 1.0.0)
: Regression testing :  Reference Course
--: unit-01-local : Avanzado: Desarrollo local de cursos
----: note-01-gh-desktop :  Uso de GitHub Desktop
----: note-02-compilar :  Compilación del sitio
cd: no such file or directory: unit-01-local
mkdir: no such file or directory: /Users/USERNAME/Documents/Regression testing/html/unit-01-local
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/USERNAME/Documents/Regression testing/html/unit-01-local/note-01-gh-desktop/index.html'
    at Object.openSync (node:fs:602:3)
    at Object.writeFileSync (node:fs:2334:35)
    at writeFile (/opt/homebrew/lib/node_modules/tutors-publish-html/node_modules/tutors-gen-lib/src/utils/utils.js:34:15)
    at publishTemplate (/opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:32:27)
    at Object.emitNote (/opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:38:9)
    at Object.emitLoPage (/opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:49:18)
    at Object.emitLo (/opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:63:18)
    at /opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:71:18
    at Array.forEach (<anonymous>)
    at Object.emitTopic (/opt/homebrew/lib/node_modules/tutors-publish-html/src/lo/html-emitter.js:70:103) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/USERNAME/Documents/Regression testing/html/unit-01-local/note-01-gh-desktop/index.html'
}
```

**Comment by tc-565** [comment]
This issue can still be replicated in tutors-publish-html@3.0.2.

**Comment by tc-565** [comment]
On further testing, other notes are being generated in the build, and can be correctly displayed if the corresponding `index.html` is opened in the directory with the compiled course. Nonetheless, these notes won't show up on the website.

This is a new issue, that might be related to the previous one.

**Comment by tc-565** [comment]
@edeleastar I think I might have figured out what triggers this issue. If there are notes in either a topic or an unit and none of them contain an image file, then this issue presents itself. If an image is added to any of those notes for each problematic topic or unit, the course builds correctly.

**Comment by edeleastar** [comment]
thanks - will look into this

**Comment by edeleastar** [comment]
Hi @tc-565 -

Thanks for providing the regression repo.
 
3.0.5 should fix this issue - see https://tutors-regression-tc-565.netlify.app/

Thanks for the report and please reopen if there is a further issue
