### ISSUE TITLE
tutors-publish-html: link in card description isn't rendered correctly

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#392]
Building a course with tutors-publish-html@3.0.1, if the description of a card contains a link formatted in markdown, such as `[text](https://github.com/)` then the card description is shown as such, instead of rendering [text](https://github.com/).

**Comment by tc-565** [comment]
This issue can still be replicated in tutors-publish-html@3.0.2.

**Comment by edeleastar** [comment]
Noted and reproduced

**Comment by edeleastar** [comment]
tutors-publish-html@3.0.3 now supports markdown in card summaries - see first card [here](https://tutors-reference-course-html.netlify.app/topic-07-reference). Unfortunately, links not currently possible - just stylistic markdown - as  the entire card is a link as currently implemented
