### ISSUE TITLE
tutors-publish-html can't create table of contents in note

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#395]
Regression in tutors-publish-html, tested in version 3.0.2. If a markdown note includes a line with the contents `[toc]`, a table of contents doesn't generate as it previously did in tutors-html.

```
[toc]
```

**Comment by edeleastar** [comment]
Hi there - thanks for the interest in our project.
Can you try
~~~
[[toc]]
~~~
Instead?

**Comment by edeleastar** [comment]
This should work

**Comment by tc-565** [comment]
Thank you! It worked, sorry for the inconvenience.
