### ISSUE TITLE
Cypress Tests: adapt existing test framework to test tutors-publish-html

### ISSUE THREAD

**Issue by edeleastar** [tutors-sdk/tutors#398]
Cypress Tests currently exercise the 'dynamic' site as generate by tutors-publish.

- [Dynamic Reference Course](https://reader.tutors.dev/course/reference-course)

The static publisher - generated by **tutors-publish-htm**l - is approaching feature parity (for course content only)

- [Static Reference Course](https://tutors-reference-course-html.netlify.app)

Documenton on using [tutors-publish-html is here](https://reader.tutors.dev/course/tutors-reference-manual#alternative-static-site-publish)

**Comment by 20041540MichaelKelly** [comment]
Git branch for this issue: **_feat/Cypress-Tests/test-tutors-publish-html-398_**

**Comment by 20041540MichaelKelly** [comment]
The addition of this lib to help with ensuring that the archive folder did indeed download but for future edge cases also.
https://www.npmjs.com/package/cy-verify-downloads
