### ISSUE TITLE
App: AB is appearing in quiet a few links

### ISSUE THREAD

**Issue by 20041540MichaelKelly** [tutors-sdk/tutors#476]
AB has been appearing in the following the links. This indicates that a lo image cannot be found.
The following links are effected:
https://reader.tutors.dev/course/wit-hdip-comp-sci-2018
https://tutors.dev/course/wit-hdip-comp-sci-2019
https://tutors.dev/course/wit-hdip-comp-sci-2020
https://tutors.dev/course/wit-hdip-comp-sci-2021
https://tutors.dev/course/wit-hdip-comp-sci-2022
https://tutors.dev/course/wit-hdip-comp-sci-2023

**Comment by edeleastar** [comment]
fixed in 2d13ba3
