### ISSUE TITLE
App: Topic Navigator Unit Links Issue

### ISSUE THREAD

**Issue by edeleastar** [tutors-sdk/tutors#477]
When navigating a topicNavigator (side bar below)
- https://tutors.dev/talk/reference-course/topic-02-side/unit-1/talk-1
Selecting a unit locates incorrect lo

**Comment by edeleastar** [comment]
Bug not apparent here: https://reader.tutors.dev/talk/reference-course/topic-02-side/unit-1/talk-1

**Comment by 20041540MichaelKelly** [comment]
The tiny addition of code now performs the same navigation as the working version linked above: https://reader.tutors.dev/talk/reference-course/topic-02-side/unit-1/talk-1

**Comment by edeleastar** [comment]
well done - closing
