### ISSUE TITLE
Navigation on homepage not showing if logged in

### ISSUE THREAD

**Issue by jouwdan** [tutors-sdk/tutors#530]
The home navigation does not have a logged in state - only shows the Login/register link even if already authenticated. Pressing this gives a 404.

![image](https://github.com/tutors-sdk/tutors/assets/76656637/edf17979-5734-4e5d-8f95-b1f6c66c3646)

![image](https://github.com/tutors-sdk/tutors/assets/76656637/9e376238-7bd2-4c16-93e1-32525f05a9c3)

**Comment by 20041540MichaelKelly** [comment]
Yeah sounds good
