### ISSUE TITLE
Missing Navigation Option from Authentication Page to Main Page

### ISSUE THREAD

**Issue by piyushbarve98** [tutors-sdk/tutors#604]
Description:
Currently, when accessing the URL tutors.dev/auth, there is no evident option or navigation link to redirect users to the main page of the Tutors.dev project. This issue is raised to address the absence of a clear pathway from the authentication page to the main page.

Details:
Implement a navigation option, such as a button or link or on clicking the tutors logo, on the authentication page that allows users to easily navigate back to the main page of tutors.dev. This enhancement aims to improve user experience and streamline navigation within the application.

![image](https://github.com/tutors-sdk/tutors/assets/69067476/c6a237da-7728-47d6-bd8f-1ee9ce0b8826)

**Comment by edeleastar** [comment]
Thanks @piyushbarve98 - this suggestion makes perfect sense. Will integrate in the next few days...

**Comment by piyushbarve98** [comment]
Hii @edeleastar I can solve this issue if you can assign it to me.

**Comment by jouwdan** [comment]
hi @piyushbarve98 happy for you to take this, i've assigned it over!

**Comment by edeleastar** [comment]
Hi @piyushbarve98 - you might have seen we reorganised the repo significantly this week. Did you have any luck?

**Comment by edeleastar** [comment]
tackled in #697 - so closing now
