### ISSUE TITLE
Readme Typos

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#61]
Fix typos in readme

**Comment by JoshBennett793** [comment]
Hi there! I'd like to contribute but wanted to let you know, the CODE-OF-CONDUCT.md link in the /main/README.md is not working. I receive an error stating `The 'tutors-sdk/tutors' repository doesn't contain the 'CODE_OF_CONDUCT.md' path in 'main'.` I also can't find it in any other branch. I understand you'd like potential contributors to read the Code of Conduct before contributing. How would you like to move forward?

**Comment by jordharr** [comment]
> Hi there! I'd like to contribute but wanted to let you know, the CODE-OF-CONDUCT.md link in the /main/README.md is not working. I receive an error stating `The 'tutors-sdk/tutors' repository doesn't contain the 'CODE_OF_CONDUCT.md' path in 'main'.` I also can't find it in any other branch. I understand you'd like potential contributors to read the Code of Conduct before contributing. How would you like to move forward?

Hi Josh

Apologies about this, code of conduct has now been added to the repo.

Thanks

**Comment by JoshBennett793** [comment]
Jordan,

Thanks for adding that.  I've submitted a PR for this issue. It's my first open-source contribution! Thanks for the opportunity!
