### ISSUE TITLE
Upgrade Mozilla PDF.js library

### ISSUE THREAD

**Issue by edeleastar** [tutors-sdk/tutors#686]
Currently the PDF component used in talk learning object:

- [PDF.js](https://mozilla.github.io/pdf.js/)
- [Talk.svelte](https://github.com/tutors-sdk/tutors/blob/development/src/lib/ui/learning-objects/content/Talk.svelte)

... is pined at version 3.x:

~~~json
    "pdfjs-dist": "3.11.174",
~~~

Version 4.x is currently not functioning with Svelte/SvelreKit due to some javascript issues. Revise the Talk object to be able to use 4.x of pdf-dist.

**Comment by lgriffin** [comment]
Fix pushed for this, required some refactoring and handling of the async loading capability but this is now resolved and working.

**Comment by edeleastar** [comment]
Closed and implemented with thanks @lgriffin
