### ISSUE TITLE
Schema for TutorsTime data store

### ISSUE THREAD

**Issue by edeleastar** [tutors-sdk/tutors#706]
Current the tutors analytics service represents student interaction using a Firebase real time NoSql document database - schema- less:

- [analytics.ts](https://github.com/tutors-sdk/tutors/blob/development/src/lib/services/analytics.ts)
- [firebase.ts](https://github.com/tutors-sdk/tutors/blob/development/src/lib/services/utils/firebase.ts)

Develop a model - postgress/supabase initially, for this data store.

**Comment by 20041540MichaelKelly** [comment]
Branch: `feature/supabase-echarts`
