### ISSUE TITLE
Abstract analytics service

### ISSUE THREAD

**Issue by edeleastar** [tutors-sdk/tutors#707]
The Analytics service:

- [analytics.ts](https://github.com/tutors-sdk/tutors/blob/development/src/lib/services/analytics.ts)

is currently bound to firebase real time database implementation. Introduce an abstraction layer to facilitate the replacement of the firebase strategy with alternative data store implementation.

This will need to be accompanied by a companion abstraction to enable the data store contents to be read and presented in TutorsTime. Current implementation is tied to firebase:

- [metrics.ts](https://github.com/tutors-sdk/tutors/blob/development/src/lib/services/types/metrics.ts)
- [https://github.com/tutors-sdk/tutors/blob/development/src/lib/services/utils/metrics.ts]

**Comment by 20041540MichaelKelly** [comment]
Branch: `feature/supabase-echarts`
