### ISSUE TITLE
Dark Mode Text Color in Footer

### ISSUE THREAD

**Issue by ki321g** [tutors-sdk/tutors#711]
The new  Text within the footer needs the color changed as it is not readable in Dark Mode

The Text that is unreadable is :

Pitch in to the [Tutors Project](https://tutors.dev/): see [Project Readme](https://github.com/tutors-sdk/tutors/blob/development/README.md), [Open Issues](https://github.com/tutors-sdk/tutors/issues) & [Gallery](https://tutors.dev/gallery)

**Comment by cdunphy** [comment]
[0]     Colm Dunphy reacted to your message:
________________________________
