### ISSUE TITLE
Search Input Field does not auto-focus on component mount

### ISSUE THREAD

**Issue by pfortune** [tutors-sdk/tutors#720]
Search Input Field does not auto-focus on component mount

**Steps to Reproduce:**
1. Navigate to a page with the search input field in the navigation bar.
2. Click on the search button to mount the search component.
3. Notice that the focus does not automatically shift to the search input field, requiring the user to manually click into the field to start typing.

**Expected Behaviour:** 
Upon the search component mounting, the focus should automatically shift to the search input field, allowing immediate typing by the user.

**Actual Behaviour:** 
The focus does not shift to the search input field automatically, necessitating an additional click to start typing.

**Additional Information:** 
This issue slightly hampers the user experience by adding an unnecessary step to begin searching.

**Comment by edeleastar** [comment]
Thanks @pfortune - this is merged now. Well done!
