### ISSUE TITLE
Allow pdf files to either categorised as  labs or lectures

### ISSUE THREAD

**Issue by maireadmeagher** [tutors-sdk/tutors#729]
I use pdf files to publish exercises - these are categorised as lectures - I would prefer them to be either categorised as 'exercises' or as a lab. 
Students get confused when the exercises appear in the lecture notes section. 
I could use (tutors) notes but I have a bank of latex generated pdf's (needing packages) so it would not be simple to post them to notes.

Thanks

**Comment by edeleastar** [comment]
Thanks @maireadmeagher, great suggestion.

implemented now - documented here: 

- https://tutors.dev/course/tutors-reference-manual#pdflab

and can be seen in action here:

- https://tutors.dev/topic/reference-course/topic-02-side
