### ISSUE TITLE
Implement cypress testing

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#81]
Implement cypress in the tutors-course-reader

**Comment by Irhutchi** [comment]
Hey @jordharr, I'll have a go setting up Cypress and creating one or two simple tests to get started.

**Comment by jordharr** [comment]
Nice one @Irhutchi - i've assigned the issue to you :)

**Comment by edeleastar** [comment]
Thats great @Irhutchi thanks! - A previous version of tutors, developed using a different framework, had an early attempt at cypress integration - see https://github.com/edeleastar/tutors-au. Not sure if there is much to be retrieved from this attempt. Happy to do a call if if suits (and I can remember what was going on in there!)

**Comment by Irhutchi** [comment]
Cheers @edeleastar that should be really helpful. I'll take a look over the weekend and get back to you once I have a better context.

**Comment by SeamusMcCarthy** [comment]
Managed to install Cypress v10.10 on a local branch and have some basic tests running against tutors-course-reader. Looking through the JSON file at the moment to see what way to approach it and what other plugins might be useful. For now, it's installed at the tutors level as I was thinking each site could have its own spec file(s). If it's only required for tutors-course-reader, let me know and I can re-install it into that folder before pushing. Will also take a look at what other plugins might be of use.

**Comment by edeleastar** [comment]
Thanks @SeamusMcCarthy - thanks for looking at this. I think we might start at the reader level only for the moment - it might be promoted to sites level eventually, but I think it may not go above that level.

**Comment by SeamusMcCarthy** [comment]
Hi @edeleastar, I've updated my local branch but when pushing I don't seem to have write access to tutors. Do I need to be added as a collaborator?

**Comment by jordharr** [comment]
@SeamusMcCarthy fork the repo & create a PR to the development branch on our repo :)

**Comment by SeamusMcCarthy** [comment]
@jordharr done, tests can be executed from the tutors-course-reader folder using 'npx cypress open' when the reader is running

**Comment by Irhutchi** [comment]
Thank Seamus for the offline help. When your PR is reviewed/merged. I'll have a look to adding to your good work.
