### ISSUE TITLE
implement eslint in course-reader packages

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#85]
implement ESLint in the tutors-course-reader & tutors-reader-lib packages

**Comment by zenby** [comment]
Hello @jordharr 

The description is a bit vague. Could you clarify a bit which exact repos / subprojects should have newly created eslint config? It seems I can start working on that issue, just want to make sure that I understand what you mean here.

Thanks!

**Comment by jordharr** [comment]
> Hello @jordharr
> 
> The description is a bit vague. Could you clarify a bit which exact repos / subprojects should have newly created eslint config? It seems I can start working on that issue, just want to make sure that I understand what you mean here.
> 
> Thanks!

Hey @zenby ! Initially the focus would be on sites/tutors-course-reader, you can use the 'getting started' section of the readme to get this up and running. Logically, it is then best to add it to it's respective lib ( components/tutors-reader-lib ). It's important that eslint recognises the typescript inside the svelte modules.

Hope this is a bit more help!

Cheers

**Comment by zenby** [comment]
Ok thanks, i'll check what I can do here! 
Please assign this issue to me.

**Comment by jordharr** [comment]
Great - much appreciated. I updated this issue to reflect the work required for it.

**Comment by edeleastar** [comment]
Hi @zenby - thanks for the interest. This guide here - https://codechips.me/eslint-svelte-typescript/ might be worth a scan, in particular for the svelte/typescript checking. It focuses in WebStorm - we would like VSCode if possible
