### ISSUE TITLE
Update tutors-home website (tutors.dev)

### ISSUE THREAD

**Issue by jordharr** [tutors-sdk/tutors#88]
Update the sections of the tutors-home website.

- Contributors section (auto generate? not sure)
- Design page - link components card to vitebook
- Changelog - Automatically get changelog from repo?

**Comment by Fan** [comment]
Some of these should be done here https://github.com/tutors-sdk/tutors/pull/123 :slightly_smiling_face:

**Comment by bonjo7** [comment]
Had a look at the change log which I added in #137 

not sure if it is what you are after and using Github actions you could automate the process in future
